"""reader platform schema visibility comments votes reports

Revision ID: 15f3b2b7daa1
Revises: 8dc0e90840e4
Create Date: 2026-07-26 04:57:28.256396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15f3b2b7daa1'
down_revision: Union[str, Sequence[str], None] = '8dc0e90840e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='open', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_reporter_id'), 'reports', ['reporter_id'], unique=False)
    op.create_index('ix_reports_status_created', 'reports', ['status', 'created_at'], unique=False)
    op.create_table('chapter_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_id', 'user_id')
    )
    op.create_index(op.f('ix_chapter_votes_chapter_id'), 'chapter_votes', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_chapter_votes_user_id'), 'chapter_votes', ['user_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_author_pinned', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comments_chapter_created', 'comments', ['chapter_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_comments_chapter_id'), 'comments', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.add_column('stories', sa.Column('visibility', sa.String(length=16), server_default='private', nullable=False))
    op.add_column('stories', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('stories', sa.Column('tags', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False))
    op.add_column('stories', sa.Column('is_adult', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('stories', sa.Column('is_showcase', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('stories', sa.Column('key_source', sa.String(length=16), server_default='user', nullable=False))
    op.add_column('stories', sa.Column('published_at', sa.DateTime(), nullable=True))
    op.create_index('ix_stories_search_gin', 'stories', [sa.literal_column("to_tsvector('simple', title || ' ' || coalesce(description, ''))")], unique=False, postgresql_using='gin')
    op.create_index('ix_stories_tags_gin', 'stories', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('ix_stories_visibility_published', 'stories', ['visibility', 'published_at'], unique=False)
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_index('ix_stories_visibility_published', table_name='stories')
    op.drop_index('ix_stories_tags_gin', table_name='stories', postgresql_using='gin')
    op.drop_index('ix_stories_search_gin', table_name='stories', postgresql_using='gin')
    op.drop_column('stories', 'published_at')
    op.drop_column('stories', 'key_source')
    op.drop_column('stories', 'is_showcase')
    op.drop_column('stories', 'is_adult')
    op.drop_column('stories', 'tags')
    op.drop_column('stories', 'description')
    op.drop_column('stories', 'visibility')
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_chapter_id'), table_name='comments')
    op.drop_index('ix_comments_chapter_created', table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_chapter_votes_user_id'), table_name='chapter_votes')
    op.drop_index(op.f('ix_chapter_votes_chapter_id'), table_name='chapter_votes')
    op.drop_table('chapter_votes')
    op.drop_index('ix_reports_status_created', table_name='reports')
    op.drop_index(op.f('ix_reports_reporter_id'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
