"""add chapter token accounting columns

Revision ID: 51d70566c242
Revises: 33c5f1dba42d
Create Date: 2026-07-26 02:33:27.965786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51d70566c242'
down_revision: Union[str, Sequence[str], None] = '33c5f1dba42d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('chapters', sa.Column('completion_tokens', sa.Integer(), nullable=True))
    op.add_column('chapters', sa.Column('cached_prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('chapters', sa.Column('token_breakdown', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapters', 'token_breakdown')
    op.drop_column('chapters', 'cached_prompt_tokens')
    op.drop_column('chapters', 'completion_tokens')
    op.drop_column('chapters', 'prompt_tokens')
    # ### end Alembic commands ###
