"""drop chapters embedding column

Eski chapters.embedding GEMINI uzayindaydi: OpenAI sorgusuyla kiyaslanamiyordu, hicbir
retrieval yolu okumuyordu ve yeni bolumlerde zaten NULL kaliyordu. Yerine chunk katmani
(chunks tablosu, OpenAI uzayi) gecti. YIKICI: downgrade kolonu geri ekler ama icindeki
eski vektorler geri GELMEZ (zaten kullanilamaz durumdaydilar).

Revision ID: 59bd97e76a61
Revises: 89ea14067cb7
Create Date: 2026-07-24 22:43:24.534150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector  # downgrade'de kolonu geri eklerken gerekiyor


# revision identifiers, used by Alembic.
revision: str = '59bd97e76a61'
down_revision: Union[str, Sequence[str], None] = '89ea14067cb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapters', 'embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
