"""add entity embeddings

Revision ID: 89ea14067cb7
Revises: 53cf5bc05d30
Create Date: 2026-07-24 22:41:34.278562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector  # characters/locations/items.embedding vector(768) kolonlari icin


# revision identifiers, used by Alembic.
revision: str = '89ea14067cb7'
down_revision: Union[str, Sequence[str], None] = '53cf5bc05d30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    op.create_index('ix_characters_embedding_hnsw', 'characters', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.add_column('items', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    op.create_index('ix_items_embedding_hnsw', 'items', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.add_column('locations', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    op.create_index('ix_locations_embedding_hnsw', 'locations', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_locations_embedding_hnsw', table_name='locations', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_column('locations', 'embedding')
    op.drop_index('ix_items_embedding_hnsw', table_name='items', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_column('items', 'embedding')
    op.drop_index('ix_characters_embedding_hnsw', table_name='characters', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_column('characters', 'embedding')
    # ### end Alembic commands ###
