"""prompt items list and per-story last chapters setting

Yazarin style/negative talimatlari tek blob olmaktan cikip SIRALI MADDE listesine tasiniyor.
VERI GOCU KRITIK: kolonlari dusurmeden ONCE mevcut blob'lar birer maddeye kopyalanir —
kimse ayarini kaybetmez. Bos/NULL blob'lar madde URETMEZ.

Revision ID: 8dc0e90840e4
Revises: 51d70566c242
Create Date: 2026-07-26 02:56:11.720516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dc0e90840e4'
down_revision: Union[str, Sequence[str], None] = '51d70566c242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('order_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_items_story_id'), 'prompt_items', ['story_id'], unique=False)
    op.add_column('stories', sa.Column('last_chapters_full_text', sa.Integer(), server_default='2', nullable=False))
    # ### end Alembic commands ###

    # --- VERI GOCU: kolonlar DUSMEDEN once blob'lari maddeye tasi ---
    # style order=0, negative order=1 (kalici kurallar uste). Sadece bosluk olanlar atlanir.
    op.execute(
        """
        INSERT INTO prompt_items (story_id, kind, text, enabled, order_index)
        SELECT id, 'style', btrim(style_prompt), true, 0
        FROM stories WHERE style_prompt IS NOT NULL AND btrim(style_prompt) <> ''
        """
    )
    op.execute(
        """
        INSERT INTO prompt_items (story_id, kind, text, enabled, order_index)
        SELECT id, 'negative', btrim(negative_prompt), true, 1
        FROM stories WHERE negative_prompt IS NOT NULL AND btrim(negative_prompt) <> ''
        """
    )

    op.drop_column('stories', 'style_prompt')
    op.drop_column('stories', 'negative_prompt')


def downgrade() -> None:
    """Downgrade schema. Maddeler tek blob'a GERI birlestirilir (yalnizca enabled olanlar,
    order sirasiyla) — geri donuste de yazarin talimatlari kaybolmaz. Kapali maddeler duser:
    blob dunyasinda "kapali madde" diye bir sey yok."""
    op.add_column('stories', sa.Column('negative_prompt', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('stories', sa.Column('style_prompt', sa.TEXT(), autoincrement=False, nullable=True))
    for kind, column in (("style", "style_prompt"), ("negative", "negative_prompt")):
        op.execute(
            f"""
            UPDATE stories s SET {column} = j.merged
            FROM (
                SELECT story_id, string_agg(text, E'\\n' ORDER BY order_index, id) AS merged
                FROM prompt_items WHERE kind = '{kind}' AND enabled GROUP BY story_id
            ) j
            WHERE s.id = j.story_id
            """
        )
    op.drop_column('stories', 'last_chapters_full_text')
    op.drop_index(op.f('ix_prompt_items_story_id'), table_name='prompt_items')
    op.drop_table('prompt_items')
