"""add chapters.backfill_attempts

Revision ID: 985355c5fb79
Revises: 3025c7b3ce29
Create Date: 2026-07-23 20:22:40.106115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '985355c5fb79'
down_revision: Union[str, Sequence[str], None] = '3025c7b3ce29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('backfill_attempts', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapters', 'backfill_attempts')
    # ### end Alembic commands ###
